openapi: 3.0.0
info:
  title: Chessbot API
  version: 0.1.0
  description: Toy API for a chess bot that can validate chess moves and do unrelated stuff.
  license:
    name: MIT
    url: https://opensource.org/license/mit/
paths:
  /games:
    post:
      summary: Start a new game
      operationId: startGame
      description: Starts a new game of chess.
      requestBody:
        $ref: '#/components/requestBodies/NewGameRequest'
      responses:
        '201':
          description: Game started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gameId:
                    type: string
                    description: Unique identifier for the game
        '400':
          description: Bad request, e.g., invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the issue

components:
  schemas:
    StartNewGameRequest:
      type: object
      properties:
        playAs:
          type: string
          description: Piece color to play as (e.g., 'white' or 'black')
          enum:
            - white
            - black
            - random
          default: random
        timeControl:
          type: string
          description: Time control for the game (e.g., 'blitz', 'rapid', 'classical')
          enum:
            - blitz
            - rapid
            - classical
          default: rapid
  requestBodies:
    NewGameRequest:
      description: Request body for starting a new game
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StartNewGameRequest'